package Engine.runtime;

/*Generated by MPS */


public class Stats {
  public static int lives = 5;
  public static int score = 0;
  public static int bonus = 5;

  public static void addScore() {
    score = score + bonus;
  }
}
